# the dockerfile is the script or the commans that are followed to build a doccker image
# The FROM statement/command pulls an image to start working off of
FROM mcr.microsoft.com/dotnet/sdk:6.0
#FROM <repo>/<user>/<image>:<tag> (tag specifies the version of a particular image, defaults to latest)

#The WORKDIR statement/command changes the working directory of the container
WORKDIR /App
# IF the specifed directory does not exist in the container, it will be created

# The COPY statement/command copies files from the host to the container
COPY ./ ./
#COPY <source/the file location of the Dockerfile><destination/inside the working directory of the container/image>

# the Run statement/command runs somethign inside the container
RUN dotnet build
#RUN <command>

# The ENTRYPOINT statement.comman specifies the command that isrun when thee container is started
ENTRYPOINT ["dotnet","./bin/Debug/net6.0/DockerDemo.dll"]